<?php

namespace Tests;

use creational\Pool\Car;
use creational\Pool\CarPool;
use PHPUnit\Framework\TestCase;

class PoolTest extends TestCase
{
    private $carPool;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->carPool = new CarPool();
    }

    public function testCanRentCar(){
        $myCar = $this->carPool->rentCar();
        $myCar2 = $this->carPool->rentCar();

        $this->assertInstanceOf(Car::class,$myCar);
        $this->assertEquals(2,$this->carPool->getReport());
    }
    public function testCanFreeCar(){
        $myCar = $this->carPool->rentCar();
        $this->carPool->freeCar($myCar);
        // myCar unset from busyCars and putted into free cars
        // So function getReport will return (count($freeCars) + count(busyCars) = 0 + 1 = 1
        $this->assertEquals(1,$this->carPool->getReport());
    }
}